// Detalhamento baseado em main.pdf, seções 3.1–3.4, páginas 5–8.
// Fórmulas do transporte/camadas complementadas pelos diagramas v4.
const op = (title, actor, input, formula, output, source) => ({title, actor, input, formula, output, source});
const OPERATIONS = [
  [
    op('Gerar pares independentes', 'Bob · local', 'Geradores de chaves dos ramos Γ e Σ.', 'Para b ∈ {Γ, Σ}:\nb.IK_B ← IdentityKeyPair()\nb.EK_B ← ECKeyPair()\nb.PQE_B ← KEMKeyPair()', 'Três pares por ramo: IK de identidade, EK clássica e PQE pós-quântica. Partes privadas permanecem em Bob.', 'Artigo msgX · §3.1 · p. 5'),
    op('Assinar e montar os bundles', 'Bob · local', 'Chaves públicas e identificadores do próprio ramo; IK privada de Bob.', 'b.Sig_B ← Sign(b.IK_B^priv, pré-chaves públicas do ramo)\nb.bundle_B ← ⟨b.IK_B^pub, b.EK_B^pub, b.PQE_B^pub, identificadores, assinaturas⟩', 'Γ e Σ têm assinaturas e identidades próprias. Sig é uma abreviação das assinaturas do bundle, não uma serialização definida pelo artigo.', 'Artigo msgX · §3.1 · p. 5'),
    op('Publicar material público', 'Bob → HS_B', 'Γ.bundle_B e Σ.bundle_B.', 'publish(Γ.bundle_B, Σ.bundle_B)', 'O HS_B guarda bundles públicos para consultas assíncronas. Não guarda ss, root keys ou chaves privadas.', 'Artigo msgX · §3.1 · p. 5')
  ],
  [
    op('Consultar Bob', 'Alice → HS_A', 'Identificação do destinatário Bob.', 'claim(Bob)', 'O HS_A recebe a solicitação dos bundles de Bob.', 'Artigo msgX · §3.1 · p. 5'),
    op('Consultar pela federação', 'HS_A → HS_B', 'Solicitação de Alice.', 'forward(claim(Bob))', 'O homeserver de Bob localiza o material público previamente publicado.', 'Artigo msgX · Figura 1 e §3.1 · pp. 4–5'),
    op('Devolver os bundles', 'HS_B → HS_A → Alice', 'Bundles públicos de Bob, identificadores e assinaturas.', 'response ← ⟨Γ.bundle_B, Σ.bundle_B⟩', 'Alice obtém material para iniciar o acordo sem exigir Bob online. A identidade recebida ainda precisa da política de confiança dos dispositivos.', 'Artigo msgX · §§3.1, 4.1–4.2 · pp. 5, 9–10')
  ],
  [
    op('Verificar assinaturas por ramo', 'Alice · local', 'Bundles de Bob; Γ.IK_B^pub e Σ.IK_B^pub.', 'verify(Γ.assinaturas, Γ.IK_B^pub)\nverify(Σ.assinaturas, Σ.IK_B^pub)\nSe qualquer verificação falhar: abortar.', 'Pré-chaves verificadas. Não há acordo de chaves nem publicação de mensagem se uma assinatura falhar.', 'Artigo msgX · §3.2 · p. 5'),
    op('Encapsular o segredo pós-quântico', 'Alice · local', 'b.PQE_B^pub para cada b ∈ {Γ, Σ}.', 'Γ.ss, Γ.ct ← Γ.KEM.Enc(Γ.PQE_B^pub)\nΣ.ss, Σ.ct ← Σ.KEM.Enc(Σ.PQE_B^pub)', 'Dois segredos ss ficam em Alice; os dois ciphertexts ct serão enviados a Bob. Encapsular gera um segredo compartilhado; não cifra a mensagem do usuário.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Executar três ECDH por ramo', 'Alice · local', 'Identidade/efêmera privadas de Alice e identidade/efêmera públicas de Bob.', 'Para b ∈ {Γ, Σ}:\nb.DH₁ ← ECDH(b.IK_A^priv, b.EK_B^pub)\nb.DH₂ ← ECDH(b.EK_A^priv, b.IK_B^pub)\nb.DH₃ ← ECDH(b.EK_A^priv, b.EK_B^pub)', 'Seis resultados ECDH ao todo: três em Γ e três em Σ. Não são publicados no servidor.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Combinar a contribuição híbrida', 'Alice · local', 'DH₁, DH₂, DH₃ e ss do mesmo ramo.', 'Γ.S ← Γ.DH₁ ‖ Γ.DH₂ ‖ Γ.DH₃ ‖ Γ.ss\nΣ.S ← Σ.DH₁ ‖ Σ.DH₂ ‖ Σ.DH₃ ‖ Σ.ss', 'Segredos combinados separados por ramo. O hibridismo acontece dentro de Γ e dentro de Σ; ainda não há cifra aninhada.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Inicializar raiz e cadeia msgX', 'Alice · local', 'Γ.S e Σ.S; salt inicial 0; rótulos de domínio distintos.', 'Γ.R₀ ‖ Γ.C₀,₀ ← HKDF(0, Γ.S, "OLM_ROOT", 64)\nΣ.R₀ ‖ Σ.C₀,₀ ← HKDF(0, Σ.S, "GC_ROOT", 64)', 'Uma raiz R₀ e uma cadeia C₀,₀ por ramo no canal individual msgX. Esses estados não são os ratchets de dados do msgGX.', 'Artigo msgX · Figura 2 · p. 6')
  ],
  [
    op('Criar o setup de grupo', 'Alice · local', 'Nova sessão de remetente msgGX.', 'setup₀ ← msgGX.newSession()', 'Material de inicialização que permite reconstruir os dois ratchets simétricos de grupo. O artigo não define a serialização dos campos do setup.', 'Artigo msgX · §§3, 3.2 · pp. 5–6'),
    op('Derivar message keys do controle', 'Alice · local', 'Γ.C₀,₀ e Σ.C₀,₀ do canal msgX.', 'Γ.M₀,₀ ← HMAC(Γ.C₀,₀, 0x1)\nΣ.M₀,₀ ← HMAC(Σ.C₀,₀, 0x3)', 'Message keys msgX específicas de cada ramo para proteger o setup. Não são as chaves usadas nas mensagens de grupo.', 'Artigo msgX · Figura 5 · p. 8'),
    op('Cifrar o setup em duas camadas', 'Alice · local', 'setup₀, Γ.M₀,₀ e Σ.M₀,₀.', 'interno ← AEAD(Γ.M₀,₀, setup₀)\nsetup₀* ← AEAD(Σ.M₀,₀, interno)', 'O simulador adota Γ por dentro e Σ por fora como convenção de visualização da dupla camada descrita no artigo. O servidor recebe o setup protegido, não seus estados secretos.', 'Artigo msgX · §3.2 · p. 6')
  ],
  [
    op('Montar a PreKeyMessage', 'Alice · local', 'Γ.ct, Σ.ct, chaves públicas de Alice e setup₀*.', 'PreKeyMessage ← ⟨Γ.ct, Σ.ct, Γ.EK_A^pub, Σ.EK_A^pub, setup₀*, contexto público⟩', 'O contexto identifica as chaves e disponibiliza as identidades públicas de Alice necessárias ao ECDH de Bob. A tupla exibida é resumida; o artigo não especifica o formato de wire completo.', 'Artigo msgX · §3.2 · p. 6'),
    op('Enviar ao homeserver local', 'Alice → HS_A', 'PreKeyMessage com setup protegido.', 'send(PreKeyMessage)', 'O HS_A recebe o envelope sem os segredos ss, S, R, C ou M.', 'Artigo msgX · Figura 1 e §3.2 · pp. 4, 6'),
    op('Rotear e entregar', 'HS_A → HS_B → Bob', 'Envelope de Alice e destino Bob.', 'forward(PreKeyMessage)\ndeliver(PreKeyMessage)', 'A federação entrega os ciphertexts KEM e o setup protegido. O transporte não substitui a autenticação criptográfica.', 'Artigo msgX · §3.2 · p. 6')
  ],
  [
    op('Decapsular nos dois ramos', 'Bob · local', 'Γ.ct, Σ.ct e as PQE privadas correspondentes.', 'Γ.ss ← Γ.KEM.Dec(Γ.ct, Γ.PQE_B^priv)\nΣ.ss ← Σ.KEM.Dec(Σ.ct, Σ.PQE_B^priv)', 'Bob recupera os mesmos segredos KEM de Alice, sem que ss tenha sido transmitido em claro.', 'Artigo msgX · §3.2 · p. 6'),
    op('Reproduzir os ECDH', 'Bob · local', 'Privadas de Bob e públicas correspondentes de Alice.', 'Para b ∈ {Γ, Σ}:\nb.DH₁ ← ECDH(b.EK_B^priv, b.IK_A^pub)\nb.DH₂ ← ECDH(b.IK_B^priv, b.EK_A^pub)\nb.DH₃ ← ECDH(b.EK_B^priv, b.EK_A^pub)', 'A correspondência ECDH produz os mesmos DH₁, DH₂ e DH₃. Estas fórmulas explicitam o processo de reprodução descrito pelo artigo.', 'Artigo msgX · §3.2 e Figura 2 · p. 6 · correspondência ECDH'),
    op('Reconstruir as derivações', 'Bob · local', 'DH₁ ‖ DH₂ ‖ DH₃ ‖ ss em cada ramo; mesmos domínios e constantes.', 'b.S ← b.DH₁ ‖ b.DH₂ ‖ b.DH₃ ‖ b.ss\nΓ.R₀ ‖ Γ.C₀,₀ ← HKDF(0, Γ.S, "OLM_ROOT", 64)\nΣ.R₀ ‖ Σ.C₀,₀ ← HKDF(0, Σ.S, "GC_ROOT", 64)\nΓ.M₀,₀ ← HMAC(Γ.C₀,₀, 0x1)\nΣ.M₀,₀ ← HMAC(Σ.C₀,₀, 0x3)', 'Bob obtém as chaves msgX necessárias para abrir o setup recebido.', 'Artigo msgX · §3.2, Figuras 2 e 5 · pp. 6, 8'),
    op('Autenticar, abrir e inicializar msgGX', 'Bob · local', 'setup₀* e as duas message keys msgX.', 'interno ← AEAD⁻¹(Σ.M₀,₀, setup₀*)\nsetup₀ ← AEAD⁻¹(Γ.M₀,₀, interno)\nmsgGX.init(setup₀)', 'Bob reconstrói a sessão de recebimento msgGX. Cada camada deve autenticar com sucesso antes de aceitar o setup.', 'Artigo msgX · §3.2 · p. 6')
  ],
  [
    op('Avançar os ratchets de dados', 'Alice · local', 'Estados simétricos Γ e Σ da sessão de remetente msgGX.', 'Γ.msgGX.ratchet.advance() → Γ.msgGX.M\nΣ.msgGX.ratchet.advance() → Σ.msgGX.M\nÍndice de mensagem compartilhado.', 'Uma message key de grupo por ramo para o próximo evento. Não executa um novo PQXDH nem um KEM por mensagem.', 'Artigo msgX · §§3, 3.3 · pp. 5–6'),
    op('Cifrar uma vez para a sala', 'Alice · local', 'Mensagem do usuário e message keys msgGX.', 'evt ← AEAD(Σ.msgGX.M, AEAD(Γ.msgGX.M, msg))', 'Um evento com duas camadas; as message keys pertencem ao plano de dados. As constantes de controle das Figuras 4–5 não especificam toda a evolução Megolm do msgGX.', 'Artigo msgX · §§3, 3.3 · pp. 5–6'),
    op('Publicar e federar o evento', 'Alice → HS_A → HS_B', 'Evento de sala protegido.', 'publish(evt)\nforward(evt)', 'Uma publicação de Alice, independentemente de G. A distribuição física do evento pelos servidores continua necessária.', 'Artigo msgX · §2 · p. 3'),
    op('Receber e abrir as duas camadas', 'HS_B → Bob; Bob · local', 'Evento e estado de recebimento msgGX correspondente.', 'deliver(evt)\nmsg ← AEAD⁻¹(Γ.msgGX.M, AEAD⁻¹(Σ.msgGX.M, evt))', 'Após autenticar e decifrar, Bob mostra a mensagem. Offline, o envelope aguarda no HS_B; nenhum estado de Bob avança até a entrega.', 'Artigo msgX · §3.3 · p. 6; fila offline didática')
  ],
  [
    op('Aplicar a política de renovação', 'Alice · local', 'Contagem R ou timeout da sessão msgGX atual.', 'Se count = R ou timeout:\n  setup_i ← msgGX.newSession()', 'Novo setup de grupo. Os canais msgX existentes são reutilizados, sem novo claim dos bundles de Bob.', 'Artigo msgX · §§3.3–3.4, 5.5 · pp. 6–7, 13'),
    op('Escolher raiz ou somente cadeia', 'Alice · local', 'Estado do canal msgX e disponibilidade de nova T pública do par.', 'Nova T do par disponível → advanceRootKey(·)\nMesmo renovador sem nova T do par → advanceChainKey(·)', 'A sessão msgGX pode mudar sem que a raiz msgX avance. Neste protótipo, os avanços de raiz pressupõem novo material do par disponível; o segundo caso é explicado, ainda não encenado.', 'Artigo msgX · §3.4 · p. 8'),
    op('Preparar ou reinjetar material PQ', 'Participantes do canal msgX', 'Índice de avanço de raiz i e período 2ᵖ (p corresponde ao N da §3.4).', 'i = 2ᵖ·n − 1: gerar PQT e enviar PQT^pub ao par\ni = 2ᵖ·n: encapsular no par; retornar ct; decapsular\nDemais índices: ss_i = null', 'Preparar PQT não reinjeta ss ainda. A fronteira PQ exige encapsulamento/retorno do ciphertext; a animação atual resume esse intercâmbio.', 'Artigo msgX · Figura 3 e §3.4 · pp. 7–8'),
    op('Derivar as novas chaves msgX', 'Alice · local', 'Raiz anterior, resultado ECDH, ss_i opcional ou cadeia anterior.', 'Se avanço de raiz:\nΓ.R_i ‖ Γ.C_i,0 ← HKDF(Γ.R_i−1, Γ.ECDH(·) ‖ Γ.ss_i, "OLM_RATCHET", 64)\nΣ.R_i ‖ Σ.C_i,0 ← HKDF(Σ.R_i−1, Σ.ECDH(·) ‖ Σ.ss_i, "GC_RATCHET", 64)\nSe somente cadeia:\nΓ.C_i,j ← HMAC(Γ.C_i,j−1, 0x2)\nΣ.C_i,j ← HMAC(Σ.C_i,j−1, 0x4)\nEm ambos os casos:\nΓ.M_i,j ← HMAC(Γ.C_i,j, 0x1)\nΣ.M_i,j ← HMAC(Σ.C_i,j, 0x3)', 'Raiz e cadeia evoluem conforme o caso. Os valores 0x2/0x4 avançam cadeias; 0x1/0x3 derivam message keys do canal msgX.', 'Artigo msgX · Figuras 3–5 · pp. 7–8'),
    op('Proteger e distribuir o novo setup', 'Alice → canais msgX → membros', 'setup_i e message keys específicas de cada canal individual.', 'Para cada m ≠ Alice:\n  setup_i*(m) ← AEAD(Σ.M_i,j(m), AEAD(Γ.M_i,j(m), setup_i))\n  send(setup_i*(m))', 'G−1 envelopes em G−1 canais, cada qual com seus estados próprios. A distribuição é O(G); o mesmo setup não implica a mesma chave ou o mesmo ciphertext em todos os canais.', 'Artigo msgX · §§3, 3.4 · pp. 5, 8')
  ],
  [
    op('Sincronizar o canal de controle', 'Bob · local', 'Material público, ciphertexts KEM quando aplicáveis e estado msgX anterior.', 'Bob reproduz o avanço de raiz ou cadeia correspondente\nΓ.M_i,j ← HMAC(Γ.C_i,j, 0x1)\nΣ.M_i,j ← HMAC(Σ.C_i,j, 0x3)', 'O receptor precisa chegar às chaves do envelope recebido. Os papéis Enc/Dec diferem na fronteira PQ, conforme a §3.4.', 'Artigo msgX · §3.4 · p. 8'),
    op('Autenticar e abrir o novo setup', 'Bob · local', 'setup_i* e as duas message keys msgX do canal Alice–Bob.', 'setup_i ← AEAD⁻¹(Γ.M_i,j, AEAD⁻¹(Σ.M_i,j, setup_i*))', 'Novo setup aceito somente após autenticar ambas as camadas. Nenhuma chave privada é enviada para abrir o envelope.', 'Artigo msgX · §3.4 · p. 8'),
    op('Reinicializar o plano de dados', 'Bob · local', 'setup_i autenticado.', 'msgGX.reinit(setup_i)\nRetornar à fase 3.', 'Nova sessão msgGX pronta para os próximos eventos. Limitar o estado comprometido depende da renovação e de material secreto novo; não é cura pós-quântica instantânea a cada mensagem.', 'Artigo msgX · §§3.4, 4.2 · pp. 8–10')
  ]
];
