// Detalhamento baseado no artigo publicado (SBSeg 2026), seções 3.1–3.4, páginas 5–8.
// Fórmulas do transporte/camadas complementadas pelos diagramas v4.
const op = (title, actor, input, formula, output, source) => ({title, actor, input, formula, output, source});
const OPERATIONS = [
  [
    op('Gerar pares independentes', 'Bob · local', 'Geradores de chaves dos ramos Γ e Σ.', 'Para b ∈ {Γ, Σ}:\nb.IK_B ← IdentityKeyPair()\nb.EK_B ← ECKeyPair()\nb.PQE_B ← KEMKeyPair()', 'Três pares por ramo: IK de identidade, EK clássica e PQE pós-quântica. Partes privadas permanecem em Bob.', 'Artigo msgX · §3.1 · p. 5'),
    op('Assinar e montar os bundles', 'Bob · local', 'Chaves públicas e identificadores do próprio ramo; IK privada de Bob.', 'b.Sig_B ← Sign(b.IK_B^priv, pré-chaves públicas do ramo)\nb.bundle_B ← ⟨b.IK_B^pub, b.EK_B^pub, b.PQE_B^pub, identificadores, assinaturas⟩', 'Γ e Σ têm assinaturas e identidades próprias. Sig representa as assinaturas que permitem verificar as pré-chaves públicas de cada ramo.', 'Artigo msgX · §3.1 · p. 5'),
    op('Publicar material público', 'Bob → HS_B', 'Γ.bundle_B e Σ.bundle_B.', 'publish(Γ.bundle_B, Σ.bundle_B)', 'O HS_B guarda bundles públicos para consultas assíncronas. Não guarda ss, root keys ou chaves privadas.', 'Artigo msgX · §3.1 · p. 5')
  ],
  [
    op('Consultar Bob', 'Alice → HS_A', 'Identificação do destinatário Bob.', 'claim(Bob)', 'O HS_A recebe a solicitação dos bundles de Bob.', 'Artigo msgX · §3.1 · p. 5'),
    op('Consultar pela federação', 'HS_A → HS_B', 'Solicitação de Alice.', 'forward(claim(Bob))\nHS_B: retirar EK_B e PQE_B de Γ/Σ do estoque disponível', 'O HS_B retira EK_B e PQE_B dos estoques de uso único de Γ/Σ e reserva a resposta para Alice. IK_B permanece disponível. Nesta demonstração, PQE também é de uso único: sua parte pública deixa de estar disponível para novos acordos após o claim.', 'Artigo msgX · Figura 1 e §3.1 · pp. 4–5; consumo de pré-chaves como política do simulador'),
    op('Entregar os bundles de Bob a Alice', 'HS_B → HS_A → Alice', 'Bundles públicos de Bob, identificadores e assinaturas.', 'response ← ⟨Γ.bundle_B, Σ.bundle_B⟩', 'Alice obtém material para iniciar o acordo sem exigir Bob online. A identidade recebida ainda precisa da política de confiança dos dispositivos.', 'Artigo msgX · §§3.1, 4.1–4.2 · pp. 5, 9–10')
  ],
  [
    op('Verificar assinaturas por ramo', 'Alice · local', 'Bundles de Bob; Γ.IK_B^pub e Σ.IK_B^pub.', 'verify(Γ.assinaturas, Γ.IK_B^pub)\nverify(Σ.assinaturas, Σ.IK_B^pub)\nSe qualquer verificação falhar: abortar.', 'Pré-chaves verificadas. Não há acordo de chaves nem publicação de mensagem se uma assinatura falhar.', 'Artigo msgX · §3.2 · p. 5'),
    op('Encapsular o segredo pós-quântico', 'Alice · local', 'b.PQE_B^pub para cada b ∈ {Γ, Σ}.', 'Γ.ss, Γ.ct ← Γ.KEM.Enc(Γ.PQE_B^pub)\nΣ.ss, Σ.ct ← Σ.KEM.Enc(Σ.PQE_B^pub)', 'Dois segredos ss ficam em Alice; os dois ciphertexts ct serão enviados a Bob. Encapsular gera um segredo compartilhado; não cifra a mensagem do usuário.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Gerar efêmeras de sessão', 'Alice · local', 'Geradores EC independentes de Γ e Σ; novo acordo com Bob.', 'Para b ∈ {Γ, Σ}:\n  b.EK_A ← ECKeyPair()\n  b.EK_A ≠ b.EK_A_bundle', 'Um novo par por ramo para este acordo. EK_A_bundle é a pré-chave publicada para receber sessões; não é reutilizada aqui. A privada de sessão é descartada após a derivação; a pública segue na PreKeyMessage.', 'Artigo msgX · §3.2 e Figura 2 · pp. 5–6; distinção de ciclo de vida da efêmera do iniciador'),
    op('Executar três ECDH por ramo', 'Alice · local', 'Identidade privada e efêmera de sessão nova de Alice; identidade e pré-chave públicas de Bob.', 'Para b ∈ {Γ, Σ}:\nb.DH₁ ← ECDH(b.IK_A^priv, b.EK_B^pub)\nb.DH₂ ← ECDH(b.EK_A^priv, b.IK_B^pub)\nb.DH₃ ← ECDH(b.EK_A^priv, b.EK_B^pub)', 'Seis resultados ECDH ao todo: três em Γ e três em Σ. Não são publicados no servidor.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Combinar a contribuição híbrida', 'Alice · local', 'DH₁, DH₂, DH₃ e ss do mesmo ramo.', 'Γ.S ← Γ.DH₁ ‖ Γ.DH₂ ‖ Γ.DH₃ ‖ Γ.ss\nΣ.S ← Σ.DH₁ ‖ Σ.DH₂ ‖ Σ.DH₃ ‖ Σ.ss', 'Segredos combinados separados por ramo. O hibridismo acontece dentro de Γ e dentro de Σ; ainda não há cifra aninhada.', 'Artigo msgX · Figura 2 · p. 6'),
    op('Inicializar raiz e cadeia msgX', 'Alice · local', 'Γ.S e Σ.S; salt inicial 0; rótulos de domínio distintos.', 'Γ.R₀ ‖ Γ.C₀,₀ ← HKDF(0, Γ.S, "OLM_ROOT", 64)\nΣ.R₀ ‖ Σ.C₀,₀ ← HKDF(0, Σ.S, "GC_ROOT", 64)', 'Uma raiz R₀ e uma cadeia C₀,₀ por ramo no canal individual msgX. Esses estados não são os ratchets de dados do msgGX.', 'Artigo msgX · Figura 2 · p. 6')
  ],
  [
    op('Criar o setup de grupo', 'Alice · local', 'Nova sessão de remetente msgGX.', 'setup₀ ← msgGX.newSession()', 'O setup reúne o material de inicialização da sessão msgGX. Ao recebê-lo e autenticá-lo, Bob pode reconstruir os dois ratchets simétricos usados para decifrar os eventos de grupo.', 'Artigo msgX · §§3, 3.2 · pp. 5–6'),
    op('Derivar message keys do controle', 'Alice · local', 'Γ.C₀,₀ e Σ.C₀,₀ do canal msgX.', 'Γ.M₀,₀ ← HMAC(Γ.C₀,₀, 0x1)\nΣ.M₀,₀ ← HMAC(Σ.C₀,₀, 0x3)', 'Message keys msgX específicas de cada ramo para proteger o setup. Não são as chaves usadas nas mensagens de grupo.', 'Artigo msgX · Figura 5 · p. 8'),
    op('Cifrar o setup em duas camadas', 'Alice · local', 'setup₀, Γ.M₀,₀ e Σ.M₀,₀.', 'interno ← AEAD(Γ.M₀,₀, setup₀)\nsetup₀* ← AEAD(Σ.M₀,₀, interno)', 'A ordem adotada pelo projeto é Γ (padrão) na camada interna e Σ (governo) na externa. Na comunicação soberana, ambas protegem o setup. Para comunicação não soberana, o projeto prevê usar apenas a camada padrão Γ; esse modo não é encenado nesta demonstração. O servidor transporta o setup cifrado.', 'Artigo msgX · §3.2 · p. 6; ordem das camadas esclarecida pelo autor do projeto')
  ],
  [
    op('Montar a PreKeyMessage', 'Alice · local', 'Identidades públicas e EK públicas de sessão de Alice, Γ.ct, Σ.ct, identificadores das pré-chaves de Bob e setup₀*.', 'PreKeyMessage ← ⟨\n  Γ.IK_A^pub, Σ.IK_A^pub,\n  Γ.EK_A^pub, Σ.EK_A^pub,\n  Γ.ct, Σ.ct,\n  ids(Γ/Σ.EK_B, Γ/Σ.PQE_B),\n  setup₀*⟩', 'IK_A^pub é necessária para Bob calcular DH₁ = ECDH(EK_B^priv, IK_A^pub). Os identificadores permitem a Bob localizar as privadas correspondentes às pré-chaves consumidas no claim. O envelope reúne esse contexto público, os ciphertexts KEM e o setup protegido.', 'Artigo msgX · §3.2 · p. 6'),
    op('Enviar ao homeserver local', 'Alice → HS_A', 'PreKeyMessage com setup protegido.', 'send(PreKeyMessage)', 'O HS_A recebe o envelope sem os segredos ss, S, R, C ou M.', 'Artigo msgX · Figura 1 e §3.2 · pp. 4, 6'),
    op('Rotear e entregar', 'HS_A → HS_B → Bob', 'Envelope de Alice e destino Bob.', 'forward(PreKeyMessage)\ndeliver(PreKeyMessage)', 'A federação entrega os ciphertexts KEM e o setup protegido. O transporte não substitui a autenticação criptográfica.', 'Artigo msgX · §3.2 · p. 6')
  ],
  [
    op('Decapsular nos dois ramos', 'Bob · local', 'Γ.ct, Σ.ct e as PQE privadas correspondentes.', 'Γ.ss ← Γ.KEM.Dec(Γ.ct, Γ.PQE_B^priv)\nΣ.ss ← Σ.KEM.Dec(Σ.ct, Σ.PQE_B^priv)', 'Bob recupera os mesmos segredos KEM de Alice, sem que ss tenha sido transmitido em claro.', 'Artigo msgX · §3.2 · p. 6'),
    op('Reproduzir os ECDH', 'Bob · local', 'Privadas de Bob e públicas correspondentes de Alice.', 'Para b ∈ {Γ, Σ}:\nb.DH₁ ← ECDH(b.EK_B^priv, b.IK_A^pub)\nb.DH₂ ← ECDH(b.IK_B^priv, b.EK_A^pub)\nb.DH₃ ← ECDH(b.EK_B^priv, b.EK_A^pub)', 'A correspondência ECDH produz os mesmos DH₁, DH₂ e DH₃. Estas fórmulas explicitam o processo de reprodução descrito pelo artigo.', 'Artigo msgX · §3.2 e Figura 2 · p. 6 · correspondência ECDH'),
    op('Reconstruir as derivações', 'Bob · local', 'DH₁ ‖ DH₂ ‖ DH₃ ‖ ss em cada ramo; mesmos domínios e constantes.', 'b.S ← b.DH₁ ‖ b.DH₂ ‖ b.DH₃ ‖ b.ss\nΓ.R₀ ‖ Γ.C₀,₀ ← HKDF(0, Γ.S, "OLM_ROOT", 64)\nΣ.R₀ ‖ Σ.C₀,₀ ← HKDF(0, Σ.S, "GC_ROOT", 64)\nΓ.M₀,₀ ← HMAC(Γ.C₀,₀, 0x1)\nΣ.M₀,₀ ← HMAC(Σ.C₀,₀, 0x3)', 'Bob obtém as chaves msgX necessárias para abrir o setup recebido.', 'Artigo msgX · §3.2, Figuras 2 e 5 · pp. 6, 8'),
    op('Autenticar, abrir e inicializar msgGX', 'Bob · local', 'setup₀* e as duas message keys msgX.', 'interno ← AEAD⁻¹(Σ.M₀,₀, setup₀*)\nsetup₀ ← AEAD⁻¹(Γ.M₀,₀, interno)\nmsgGX.init(setup₀)', 'Bob reconstrói a sessão de recebimento msgGX. Cada camada deve autenticar com sucesso antes de aceitar o setup.', 'Artigo msgX · §3.2 · p. 6'),
    op('Apagar as privadas das pré-chaves consumidas', 'Bob · local', 'Acordo concluído e setup autenticado; Γ/Σ EK_B e PQE_B já usadas.', 'Para b ∈ {Γ, Σ}:\n  apagar b.EK_B^priv\n  apagar b.PQE_B^priv\n  manter b.IK_B^priv e o estado derivado msgX/msgGX', 'O modelo marca as privadas como apagadas após concluir o acordo. O descarte ilustra uma condição de FS; não apaga a identidade nem demonstra proteção contra comprometimento do estado atual. PQE é de uso único por escolha deste simulador.', 'Artigo msgX · §§3.1–3.2 · pp. 5–6; política didática de descarte')
  ],
  [
    op('Avançar os ratchets de dados', 'Alice · local', 'Estados simétricos Γ e Σ da sessão de remetente msgGX.', 'Γ.msgGX.ratchet.advance() → Γ.msgGX.M\nΣ.msgGX.ratchet.advance() → Σ.msgGX.M\nÍndice de mensagem compartilhado.', 'Uma message key de grupo por ramo para o próximo evento. Não executa um novo PQXDH nem um KEM por mensagem.', 'Artigo msgX · §§3, 3.3 · pp. 5–6'),
    op('Cifrar uma vez para a sala', 'Alice · local', 'Mensagem do usuário e message keys msgGX.', 'evt ← AEAD(Σ.msgGX.M, AEAD(Γ.msgGX.M, msg))', 'Um evento protegido por Γ na camada interna e Σ na externa. As chaves de mensagem são derivadas dos ratchets de dados msgGX, separados das cadeias de controle msgX que protegem os setups.', 'Artigo msgX · §§3, 3.3 · pp. 5–6'),
    op('Publicar e federar o evento', 'Alice → HS_A → HS_B', 'Evento de sala protegido.', 'publish(evt)\nforward(evt)', 'Uma publicação de Alice, independentemente de G. A distribuição física do evento pelos servidores continua necessária.', 'Artigo msgX · §2 · p. 3'),
    op('Receber e abrir as duas camadas', 'HS_B → Bob; Bob · local', 'Evento e estado de recebimento msgGX correspondente.', 'deliver(evt)\nmsg ← AEAD⁻¹(Γ.msgGX.M, AEAD⁻¹(Σ.msgGX.M, evt))', 'Após autenticar e decifrar, Bob mostra a mensagem. Offline, o envelope aguarda no HS_B; nenhum estado de Bob avança até a entrega.', 'Artigo msgX · §3.3 · p. 6; fila offline didática')
  ],
  [
    op('Aplicar a política de renovação', 'Alice · local', 'Contagem R ou timeout da sessão msgGX atual.', 'Se count = R ou timeout:\n  setup_s ← msgGX.newSession()', 'Novo setup de grupo. Os canais msgX existentes são reutilizados, sem novo claim dos bundles de Bob.', 'Artigo msgX · §§3.3–3.4, 5.5 · pp. 6–7, 13'),
    op('Verificar a ausência de nova T de Bob', 'Alice · local', 'Canal msgX estabelecido; Bob apenas recebe neste cenário.', 'Sem nova T pública de Bob:\n  manter Γ.R_i e Σ.R_i\n  executar advanceChainKey em cada ramo', 'A renovação da sessão msgGX não avança o índice de raiz i. Não há ECDH novo, preparação PQ ou reinjeção PQ nesta execução.', 'Artigo msgX · §3.4 e Figura 4 · p. 8'),
    op('Avançar somente as cadeias msgX', 'Alice · local', 'Γ.C_i,j−1 e Σ.C_i,j−1; raízes preservadas.', 'Γ.C_i,j ← HMAC(Γ.C_i,j−1, 0x2)\nΣ.C_i,j ← HMAC(Σ.C_i,j−1, 0x4)\ni permanece constante; j avança.', 'Os ramos evoluem por HMAC. O contador de sessões msgGX é separado de i e j do canal msgX.', 'Artigo msgX · Figura 4 · p. 8'),
    op('Derivar novas message keys msgX', 'Alice · local', 'Cadeias atualizadas Γ.C_i,j e Σ.C_i,j.', 'Γ.M_i,j ← HMAC(Γ.C_i,j, 0x1)\nΣ.M_i,j ← HMAC(Σ.C_i,j, 0x3)', 'Novas chaves de controle protegem o próximo setup. O avanço simétrico não demonstra recuperação após comprometimento do estado da cadeia.', 'Artigo msgX · Figura 5 e §4.2 · pp. 8–10'),
    op('Proteger e distribuir o novo setup', 'Alice → canais msgX → membros', 'setup_s e message keys específicas de cada canal individual.', 'Para cada m ≠ Alice:\n  setup_s*(m) ← AEAD(Σ.M_i,j(m), AEAD(Γ.M_i,j(m), setup_s))\n  send(⟨setup_s*(m)⟩)\n\nFormato didático quando há troca de ratchet (não executado aqui):\n  send(⟨{b.T_i^pub}_b, [{b.PQT_i^pub}_b | {b.ct_i}_b], setup_s*⟩)\n  b ∈ {Γ, Σ}; campos PQ opcionais conforme a etapa\n  s = sessão msgGX; i = etapa de raiz msgX', 'Nesta execução não são anexadas novas T, PQT ou ct: só a cadeia avança. Em um avanço de raiz, T privada anterior e T pública recebida alimentam ECDH; PQT pública prepara o KEM e ct retorna seu encapsulamento nas etapas correspondentes. A notação destaca o material público transportado e o setup protegido em cada envelope. G−1 envelopes em G−1 canais, cada qual com seus estados próprios. A distribuição é O(G); o mesmo setup não implica a mesma chave ou o mesmo ciphertext em todos os canais.', 'Artigo msgX · §§3, 3.4 · pp. 5, 8')
  ],
  [
    op('Avançar as cadeias de recebimento', 'Bob · local', 'Envelope de renovação de Alice e estado msgX anterior; nenhuma nova T ou ciphertext KEM.', 'Γ.C_i,j ← HMAC(Γ.C_i,j−1, 0x2)\nΣ.C_i,j ← HMAC(Σ.C_i,j−1, 0x4)\nΓ.M_i,j ← HMAC(Γ.C_i,j, 0x1)\nΣ.M_i,j ← HMAC(Σ.C_i,j, 0x3)', 'Bob mantém as raízes e reproduz somente o avanço de cadeia. Offline, esse avanço aguarda a entrega do envelope, em ordem.', 'Artigo msgX · §3.4, Figuras 4–5 · p. 8'),
    op('Autenticar e abrir o novo setup', 'Bob · local', 'setup_s* e as duas message keys msgX do canal Alice–Bob.', 'setup_s ← AEAD⁻¹(Γ.M_i,j, AEAD⁻¹(Σ.M_i,j, setup_s*))', 's identifica a sessão msgGX; i,j identificam o estado msgX. Novo setup aceito somente após autenticar ambas as camadas. Nenhuma chave privada é enviada para abrir o envelope.', 'Artigo msgX · §3.4 · p. 8'),
    op('Reinicializar o plano de dados', 'Bob · local', 'setup_s autenticado.', 'msgGX.reinit(setup_s)\nRetornar à fase 3.', 'Nova sessão msgGX pronta para os próximos eventos. Limitar o estado comprometido depende da renovação e de material secreto novo; não é cura pós-quântica instantânea a cada mensagem.', 'Artigo msgX · §§3.4, 4.2 · pp. 8–10')
  ]
];
